### ISSUE TITLE
Test suite should include tests of simple Gaussian GBM

### ISSUE THREAD

**Issue by phelps-sg** [anabugaenko/hurstexponent#11]
I think the code below from the simple_series function is meant to scale the returns, but in fact it  adds iid noise to the *prices*.

~~~python
 # Scale the random changes by the desired standard deviation as a percentage of the mean value
    series += np.random.randn(length) * noise_pct_std * np.std(series)

~~~

**Comment by phelps-sg** [comment]
So the comment for the function says:

~~~
Generate a synthetic time series using a random walk model with added Gaussian noise
~~~

but _why_ do we want Guassian noise _added_ to the prices?  This isn't typically what we observe when we work with financial data?

**Comment by phelps-sg** [comment]
If we add Guassian noise to the price series, then we always have non-zero probability of generating *negative* prices at any time period, therefore this does not constitute a geometric random walk.

**Comment by anabugaenko** [comment]
<img width="807" alt="Screenshot 2023-09-17 at 06 12 06" src="https://github.com/anabugaenko/hurstexponent/assets/6001401/589eb7e1-1ade-46c1-bc86-25e780f12b6b">

**Comment by anabugaenko** [comment]
This noise term can help unpredictable, short-term fluctuations in prices: because financial time series often exhibit volatilities that change over time, the idea here was to introduce an additive noise component scaled by the series' standard deviation, the model can emulate periods of varying volatility at short intraday time frames. However, a caveat to remember is the risk of negative prices.

Solution - apply a post-processing step to correct negative values after generating the series with additive noise.

**Comment by anabugaenko** [comment]
If you try removing it and plotting the series generated you'll see issues with the type of non-noised series generated: Options:

- Take absolute 
- Replace any negative value with the previous value
-  All negative values are set to a small positive constant.
- Zeroing them out

**Comment by phelps-sg** [comment]
In order to test the Hurst estimators, it is important to use a simple data generating process, where you know that the actual Hurst exponent is 0.5, as one of the tests in the suite.  Doing so allows you to test whether the estimator is unbiased (expected value of estimator is 0.5) and to compare the confidence intervals against those reported in the literature based on both theoretical and Monte-Carlo analyses.  The best way to do this is to repeat the replicate at least of the subset of the analysis of Weron (2002) where he uses Monte-Carlo to estimate the CI of GBM, i.e. a cumulative product of iid. Gaussian returns.

Yes it will *also* be important to incorporate high-frequency price processes into the test suite, particularly if application to high-frequency data is the intended end use-case.  This will allow you to assess whether the estimator is indeed robust to microstructure-noise, heavy-tailed return distributions etc..  E.g. for the latter, you could incorporate some of the results from e.g. Barunik and Kristoufek (2010) as assertions into the test suite.  Note that to do this you will need a separate test using a process that makes use of heavy-tailed noise for the innovations.  

In general, it will make sense to use a variety of price processes in the test-suite and to assert that your estimator gives results that are consistent with those reported elsewhere in the literature.  However it is important that at least one of the processes you simulate is simple Gaussian GBM.

Barunik, Jozef, and Ladislav Kristoufek. "On Hurst exponent estimation under heavy-tailed distributions." Physica A: statistical mechanics and its applications 389.18 (2010): 3844-3855.

**Comment by anabugaenko** [comment]
Yes, as accounted for in when cumprod set to True 

# Much of this function generalises Dmitry Motti's implementation of a random walk process, specifically around line 197
# at https://github.com/Mottl/hurst/blob/master/hurst/__init__.py. Key improvements around proba, which appears stale in
# the latter.
def stochastic_process(length: int = 99999, proba: float = 0.5, min_lag: int = 10, max_lag: int = 100, cumprod: bool = False, seed: int = None) -> List[float]:
    """
    Generates a stochastic process

    Parameters
    ----------
    length : int
        Length of the random walk series.
    proba : float, default 0.5
        The probability that the next increment will follow the trend.
        Set proba > 0.5 for the persistent random walk,
        set proba < 0.5 for the antipersistent one.
    min_lag : int, default 10
    max_lag : int, default 100
        Minimum and maximum lag sizes to calculate trend direction.
    cumprod : bool, default False
        Generate a random walk as a cumulative product instead of cumulative sum.
    seed : int, optional
        Random seed used to initialize the pseudo-random number generator.

    Returns
    -------
    series : List[float]
        Generated random walk process.
    """
    assert(min_lag >= 1)
    assert(max_lag >= min_lag)

    if max_lag > length:
        max_lag = length
        warnings.warn("max_lag has been set to the length of the series.")

    if seed is not None:
        np.random.seed(seed)

    series = np.zeros(length, dtype=float)
    series[0] = 1. if cumprod else 0.

    for i in range(1, length):
        if i < min_lag + 1:
            direction = np.sign(np.random.randn())
        else:
            lag = np.random.randint(min_lag, min(i-1, max_lag) + 1)
            direction = np.sign(series[i-1] / series[i-1-lag] - 1.) if cumprod else np.sign(series[i-1] - series[i-1-lag])
            direction *= np.sign(proba - np.random.uniform())

        increment = np.abs(np.random.randn())
        if cumprod:
            series[i] = series[i-1] * np.abs(1 + increment / 1000. * direction)
        else:
            series[i] = series[i-1] + increment * direction

    return series


Which is what's tested on bootstrap.
