### ISSUE TITLE
mle fitting method in standard_hurst returns incorrect estimate

### ISSUE THREAD

**Issue by phelps-sg** [anabugaenko/hurstexponent#16]
If we modify `initial_guess` from 0.5 to 0.1 in the code below then estimating using standard_hurst always give us results very close to $\hat{H} = 0.1$ irrespective of the data.

~~~python
 if fitting_method == "mle":
        bounds = [(0, 1), (-np.inf, np.inf)]
        initial_guess = [0.5, 0]  # Guess for both H and c
        result = minimize(
            neg_log_likelihood,
            initial_guess,
            args=(np.array(valid_lags), np.array(y_values), _hurst_function),
            bounds=bounds,
        )
        H, c = result.x
~~~

**Comment by phelps-sg** [comment]
This explains #14.  The reason the confidence intervals are so small for standard_hurst with default fitting method is because the estimates are always equal to the initial guess (0.5) irrespective of the sample.

**Comment by anabugaenko** [comment]
Resolved via new fitting method: Any issues resulting from the fitting method should be raised in powerlaw-function package.
