### ISSUE TITLE
Comparision with zero in standard_hurst ignores floating point precision

### ISSUE THREAD

**Issue by phelps-sg** [anabugaenko/hurstexponent#18]
The following code in standard_hurst attempts to test for zero mean, but mean is unlikely to be exactly zero due to finite precision of floating point.  Use `np.isclose`.

~~~python
mean = np.mean(series)
if mean != 0:
   ...
~~~

should be

~~~python
if not np.isclose(mean, 0.0):
   ...
~~~

**Comment by anabugaenko** [comment]
Resolved
